config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  post 'welcome/calculate_black_scholes', as: 'black_scholes_reports'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/black_scholes_calculation.rb
module BlackScholesCalculation
	extend ActiveSupport::Concern

  def ndist(z)
    (1.0/(Math.sqrt(2*Math::PI)))*Math.exp(-0.5*z)
  end

  def n(z)
    b1 =  0.31938153
    b2 = -0.356563782
    b3 =  1.781477937
    b4 = -1.821255978
    b5 =  1.330274429
    p  =  0.2316419
    c2 =  0.3989423

    a = z.abs

    return 1.0 if a > 6.0

    t = 1.0/(1.0+a*p)
    b = c2*Math.exp((-z)*(z/2.0))
    n = ((((b5*t+b4)*t+b3)*t+b2)*t+b1)*t
    n = 1.0-b*n

    n = 1.0 - n if z < 0.0

    n
  end

  def black_scholes(c,s,x,r,v,t)
    sqt = Math.sqrt(t)

    d1 = (Math.log(s/x) + r*t)/(v*sqt) + 0.5*(v*sqt)
    d2 = d1 - (v*sqt)

    if c == 'call'
      delta = n(d1)
      nd2 = n(d2)
    else
      delta = -n(-d1)
      nd2 = -n(-d2)
    end

    ert = Math.exp(-r*t)
    nd1 = ndist(d1)

    gamma = nd1/(s*v*sqt)
    vega = s*sqt*nd1
    theta = -(s*v*nd1)/(2*sqt) - r*x*ert*nd2
    rho = x*t*ert*nd2

    price = s*delta-x*ert*nd2

    {price: price, gamma: gamma, vega: vega, theta: theta, rho: rho, delta: delta}
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  include BlackScholesCalculation
  include ActionView::Helpers::NumberHelper

  def index

  end

  def calculate_black_scholes
  	c = params[:call_or_put]
  	s = params[:stock_price].to_i
  	x = params[:strike_price].to_i
  	r = params[:interest_rate].to_i
  	v = params[:volatility].to_i
  	t = (DateTime.strptime(params[:maturity_date], "%m/%d/%Y %H:%M %P").mjd - DateTime.now.mjd)/356
  	@a = black_scholes(c,s,x,r,v,t)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>BlackScholes</title>
	  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	  <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">Black Scholes Model</a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li class="active"><a href="/">Home</a></li>
		    </ul>
		  </div>
		</nav>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/welcome/_price_table.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>PREMIUM</th>
        <th>GAMMA</th>
        <th>VEGA</th>
        <th>THETA</th>
        <th>DELTA</th>
        <th>RHO</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= number_with_precision(black_scholes_data[:price], precision: 2) %></td>
        <td><%= number_with_precision(black_scholes_data[:gamma], precision: 2) %></td>
        <td><%= number_with_precision(black_scholes_data[:vega], precision: 2) %></td>
        <td><%= number_with_precision(black_scholes_data[:theta], precision: 2) %></td>
        <td><%= number_with_precision(black_scholes_data[:delta], precision: 2) %></td>
        <td><%= number_with_precision(black_scholes_data[:rho], precision: 2) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/welcome/calculate_black_scholes.js.erb
$('#black_scholes_report').html("<%= j render(partial: 'price_table', locals: {black_scholes_data: @a}) %>")

app/views/welcome/index.html.erb
<h1 class="col-md-offset-3">BLACK & SCHOLES MODEL</h1>
<br>
<%= form_tag black_scholes_reports_path, method: :post, id: 'black_scholes_form', "class"=> 'role form-horizontal', :remote => true do %>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description">STOCK PRICE</label>
	  <div class="col-md-4">
	    <%= number_field_tag :stock_price, "", class: 'form-control' %>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description">SPOT PRICE</label>
	  <div class="col-md-4">
	    <%= number_field_tag :strike_price, "", class: 'form-control' %>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description">MATURITY DATE</label>
	  <div class="col-md-4">
	    <%= text_field_tag :maturity_date, "", class: 'form-control form_datetime' %>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description">VOLATILITY (%)</label>
	  <div class="col-md-4">
	    <%= number_field_tag :volatility, "", class: 'form-control' %>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description">INTEREST (%)</label>
	  <div class="col-md-4">
	    <%= number_field_tag :interest_rate, "", class: 'form-control' %>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label" for="request-description"></label>
	  <div class="col-md-4">

			<label class="radio-inline">
	      <%= radio_button_tag :call_or_put, 'call', checked: true %> Call
	    </label>
	    <label class="radio-inline">
	      <%= radio_button_tag :call_or_put, 'put' %> Put
	    </label>
	  </div>
	</div>
	<div class="form-group">
	  <label class="col-md-4 control-label"></label>
	  <div class="col-md-4">
	    <%= submit_tag "CALCULATE", class: 'btn btn-info' %>
	  </div>
	</div>
<% end %>
<div id="black_scholes_report">
</div>
<script type="text/javascript">
	$(document).ready(function () {
		$(".form_datetime").datetimepicker();
	});
</script>